const assert = require('node:assert/strict');
const brain = require('../src/embedded-brain');
const first = brain.answer({ message: 'Necesito una función en JavaScript', history: [], memories: [], webResults: [] });
assert.equal(first.domain, 'programming'); assert.match(first.text, /function sumar/); assert.ok(first.usedTools.includes('neural-weights'));
const second = brain.answer({ message: '¿Podés profundizar?', history: [{ role: 'assistant', content: first.text }], memories: [], webResults: [] });
assert.equal(second.intent, 'deep'); assert.ok(second.text.includes('profundicemos'));
const quantum = brain.answer({ message: '¿Qué es la superposición cuántica?', history: [], memories: [], webResults: [] });
assert.equal(quantum.domain, 'quantum'); assert.match(quantum.text, /superposición|Superposición/);
const why = brain.answer({ message: '¿Por qué es importante validar entradas?', history: [], memories: [], webResults: [] });
const how = brain.answer({ message: '¿Cómo puedo validar entradas?', history: [], memories: [], webResults: [] });
assert.notEqual(why.text, how.text); assert.ok(why.text.length > 80 && how.text.length > 80);
const learned = brain.answer({ message: '¿Qué es un concepto nuevo?', history: [], memories: [], webResults: [{ title: 'Fuente', snippet: 'Una explicación aprendida del concepto nuevo.' }] });
assert.match(learned.text, /información nueva/); console.log('brain ok', JSON.stringify({ programming: first.confidence, followUp: second.intent, quantum: quantum.confidence, varied: why.text !== how.text }));
