const fs = require('node:fs');
const path = require('node:path');
const { classifyDomain, classifyIntent, rankContext, weights } = require('./neural-engine');
const knowledge = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'brain', 'knowledge.json'), 'utf8'));
function normalize(text) { return String(text).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); }
function hash(text) { return [...normalize(text)].reduce((n, c) => (n * 31 + c.charCodeAt(0)) >>> 0, 7); }
function memoryText(memory) { if (memory.type !== 'learned_research') return memory.content; try { const learned = JSON.parse(memory.content); return learned.learned?.map(item => `${item.title}: ${item.snippet}`).join(' ') || memory.content; } catch { return memory.content; } }
function selectedFacts(facts, message, count = 3) { const query = normalize(message); const matching = facts.filter(f => normalize(f).split(/\W+/).some(word => word.length > 5 && query.includes(word))); const start = hash(message) % facts.length; const varied = Array.from({ length: facts.length }, (_, i) => facts[(start + i) % facts.length]); return [...new Set([...matching, ...varied])].slice(0, Math.min(count, facts.length)); }
function codeAnswer(message, domain) { const query = normalize(message); const examples = domain.examples || {}; const language = query.includes('python') ? 'python' : query.includes('node') ? 'node' : 'javascript'; const example = examples[language] || examples.javascript; const lead = query.includes('error') || query.includes('bug') ? 'Para depurarlo, primero aislá el caso que falla y validá los datos de entrada.' : query.includes('api') ? 'Para una API conviene separar rutas, validación, lógica de negocio y persistencia.' : 'Para construirlo de forma mantenible, separá la responsabilidad en funciones pequeñas.'; return `${lead}\n\n${domain.intro}\n\nEjemplo en ${language}:\n\n\`\`\`${language}\n${example}\n\`\`\`\n\nDespués de implementarlo: validá entradas, probá casos normales y errores, y no guardes secretos en el código.`; }
function webSynthesis(webResults) { const text = webResults.slice(0, 3).map(r => r.snippet || r.title).filter(Boolean).join(' '); return text.length > 650 ? `${text.slice(0, 647)}…` : text; }
function answer({ message, history = [], memories = [], webResults = [] }) { const domainResult = classifyDomain(message, history); const intentResult = classifyIntent(message); const domain = knowledge.domains[domainResult.label] || knowledge.domains.general; const related = rankContext(message, history, memories); const query = normalize(message); const facts = selectedFacts(domain.facts, message, query.includes('por que') || query.includes('como') ? 3 : 4); let response;
  if (intentResult.label === 'greeting') response = 'Hola. Soy JARVIS. ¿Qué querés resolver hoy? Puedo razonar sobre el contexto de este chat, ayudarte a programar o explicarte conceptos paso a paso.';
  else if (intentResult.label === 'deep' && related.length) response = `Sí, profundicemos. La idea central es esta:\n\n${memoryText(related[0])}\n\nEn términos más simples: ${domain.intro} ${facts[0]}`;
  else if (intentResult.label === 'code' && domainResult.label === 'programming') response = codeAnswer(message, domain);
  else if (intentResult.label === 'compare') response = `La diferencia principal depende del criterio que quieras usar. En el contexto de ${domainResult.label}, podés separar la comparación así:\n\n• Concepto: ${facts[0]}\n• Aplicación: ${facts[1] || facts[0]}\n• Límite: ${facts[2] || 'el resultado depende de los supuestos del problema.'}`;
  else if (query.includes('por que') || query.includes('porque')) response = `La razón principal es que ${facts[0].toLowerCase()}\n\nAdemás, ${facts[1] || facts[0]} Esto muestra por qué el contexto y los supuestos importan.`;
  else if (query.includes('como') || query.includes('qué hago') || query.includes('que hago')) response = `Podés abordarlo en tres pasos:\n\n1. Identificá el concepto: ${facts[0]}\n2. Aplicalo al caso concreto: ${facts[1] || facts[0]}\n3. Verificá el resultado: ${facts[2] || 'revisá los supuestos y los casos límite.'}`;
  else response = `${domain.intro}\n\n${facts.map(f => `• ${f}`).join('\n')}`;
  const context = related.filter(x => x.relevance > 0.25).slice(0, 2).map(x => memoryText(x)); if (context.length && intentResult.label !== 'deep') response += `\n\nLo conecto con lo que veníamos hablando:\n${context.map(x => `• ${x}`).join('\n')}`;
  if (memories.length) { const learned = memories.filter(m => m.type === 'learned_research').slice(0, 2).map(memoryText); if (learned.length) response += `\n\nEsto es parte de lo que aprendí antes sobre el tema:\n${learned.map(x => `• ${x}`).join('\n')}`; }
  if (webResults.length) response += `\n\nEncontré información nueva y la integré a la explicación:\n${webSynthesis(webResults)}`;
  return { text: response, usedTools: ['embedded-brain', 'neural-weights', 'context-engine', ...(webResults.length ? ['learned-web-context'] : [])], domain: domainResult.label, intent: intentResult.label, confidence: domainResult.probabilities[domainResult.label] };
}
function localModelAvailable() { return true; }
module.exports = { answer, localModelAvailable, classifyDomain, classifyIntent, detectDomain: classifyDomain, detectIntent: classifyIntent, knowledge, weights };
