const fs = require('node:fs');
const path = require('node:path');
const weights = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'brain', 'weights.json'), 'utf8'));
function normalize(text) { return String(text).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); }
function tokenize(text) { return normalize(text).split(/[^a-z0-9ñ]+/).filter(Boolean); }
function vectorize(text) { const tokens = tokenize(text); const counts = new Array(weights.vocabulary.length).fill(0); for (const token of tokens) { const index = weights.vocabulary.indexOf(token); if (index >= 0) counts[index] += 1; } const norm = Math.sqrt(counts.reduce((sum, x) => sum + x * x, 0)) || 1; return counts.map(x => x / norm); }
function softmax(values) { const max = Math.max(...values); const exps = values.map(x => Math.exp(x - max)); const sum = exps.reduce((a,b) => a + b, 0) || 1; return exps.map(x => x / sum); }
function classifyDomain(text, history = []) { const vector = vectorize([...history.slice(-6).map(x => x.content), text].join(' ')); const raw = weights.domainWeights.map((row, domainIndex) => row.reduce((sum, weight, i) => sum + weight * (vector[i] || 0), weights.bias[weights.domains[domainIndex]] || 0)); const probabilities = softmax(raw); const index = probabilities.indexOf(Math.max(...probabilities)); return { label: weights.domains[index] || 'general', probabilities: Object.fromEntries(weights.domains.map((d, i) => [d, Number(probabilities[i].toFixed(4))])) }; }
function classifyIntent(text) { const normalized = normalize(text); const vector = vectorize(text); const labels = Object.keys(weights.intentWeights); const raw = labels.map(label => weights.intentWeights[label].reduce((sum, weight, i) => sum + weight * (vector[i] || 0), 0)); const greeting = /^(hola|buenas|buen dia|hey|saludos)\b/.test(normalized); if (!greeting) raw[labels.indexOf('greeting')] = -10; if (/profund|detalle|amplia|ejemplo|no entendi|no entiendo/.test(normalized)) raw[labels.indexOf('deep')] += 3; if (/diferencia|comparar|versus|\bvs\b/.test(normalized)) raw[labels.indexOf('compare')] += 3; if (/escribe|crea|implementa|programa|codigo|funcion|endpoint|script/.test(normalized)) raw[labels.indexOf('code')] += 3; const probabilities = softmax(raw); const index = probabilities.indexOf(Math.max(...probabilities)); return { label: labels[index] || 'answer', probabilities: Object.fromEntries(labels.map((d, i) => [d, Number(probabilities[i].toFixed(4))])) }; }
function contextVector(history = [], memories = []) { return vectorize([...history.slice(-12).map(x => x.content), ...memories.slice(0, 5).map(x => x.content)].join(' ')); }
function similarity(a, b) { return a.reduce((sum, x, i) => sum + x * (b[i] || 0), 0); }
function rankContext(message, history = [], memories = []) { const query = vectorize(message); return [...history.map(x => ({ ...x, kind: 'conversation' })), ...memories.map(x => ({ ...x, kind: 'memory' }))].map(item => ({ ...item, relevance: similarity(query, vectorize(item.content)) })).sort((a,b) => b.relevance - a.relevance).slice(0, 8); }
function needsWebSearch(message, domainResult, intentResult) { const normalized = normalize(message); if (intentResult.label === 'greeting') return false; if (/(internet|busca|buscar|fuentes|actual|actualidad|hoy|noticia|último|ultimo|reciente|fecha|precio)/.test(normalized)) return true; const known = tokenize(message).filter(token => weights.vocabulary.includes(token)).length; return domainResult.label === 'general' || domainResult.probabilities[domainResult.label] < 0.55 || known === 0; }
module.exports = { weights, tokenize, vectorize, softmax, classifyDomain, classifyIntent, contextVector, rankContext, needsWebSearch };
